name: test
on: push
  # pull_request:
  #   branches:
  #    - main
  # push:
  #   branches:
  #    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: KCL Installation
        run: wget -q https://kcl-lang.io/script/install-cli.sh -O - | /bin/bash

      - uses: actions/setup-go@v1
        with:
          go-version: "1.19"

      # - name: Example tests
      #   shell: bash -ieo pipefail {0}
      #   run: PATH=$PATH:$HOME/go/bin ./scripts/test.sh
      
      - name: Run KCL in specific directory
        run: |
          cd ./examples/server/app_sidecar/prod
          kcl run > kcl_output.txt 2>&1
        shell: /usr/bin/bash -e {0}

      - name: Upload KCL output
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: kcl-output
          path: ./examples/server/app_sidecar/prod/kcl_output.txt