name: test
on: push
  # pull_request:
  #   branches:
  #    - main
  # push:
  #   branches:
  #    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: KCL Installation
        run: wget -q https://kcl-lang.io/script/install-cli.sh -O - | /bin/bash

      - uses: actions/setup-go@v1
        with:
          go-version: "1.22"

      # - name: Example tests
      #   # shell: bash -ieo pipefail {0}
      #   run: PATH=$PATH:$HOME/go/bin ./scripts/test.sh

      - name: Run KCL in specific directory 1
        run: |
          cd ./examples/appops/nginx-example/dev
          PATH=$PATH:$HOME/go/bin
          kcl run

      - name: Run KCL in specific directory
        run: |
          cd ./examples/server/app_sidecar/prod
          PATH=$PATH:$HOME/go/bin
          kcl run